# Generated by Django 4.2.1 on 2023-06-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0031_alter_registereddata_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereddata',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_cou_reg.coursedata'),
        ),
    ]
