# Generated by Django 4.2.1 on 2023-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0032_alter_registereddata_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddata',
            name='date_apply',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registereddata',
            name='date_approve',
            field=models.DateTimeField(null=True),
        ),
    ]
